### ISSUE TITLE
Chromedriver.exe not executable on linux

### ISSUE THREAD

**Issue by DanGiaime** [makiisthenes/TiktokAutoUploader#10]
This is an amazing library.

You mentioned you custom compiled the chromedriver exe - could you make a seperate build for linux?

Trying to use this on linux but getting EXEC error (not due to permissions) because it seems to not be built for linux.

If you don't have the time, I'd be happy to do it if you can instruct on what needs to be done :D

**Comment by makiisthenes** [comment]
Hi there, thanks. I will give the Linux version of chromedriver and also instructions on how to modify it on newer versions to avoid detection.
