### ISSUE TITLE
#launching error

### ISSUE THREAD

**Issue by thanhtuvietnam** [makiisthenes/TiktokAutoUploader#11]
Exception has occurred: ImportError
cannot import name 'Mapping' from 'collections' (C:\Python310\lib\collections\__init__.py)
  File "C:\Users\ADMIN\Desktop\python scripts\TiktokAutoUploader-master\Browser.py", line 1, in <module>
    import undetected_chromedriver.v2 as uc

**Comment by thanhtuvietnam** [comment]
help me please, sir!!!

**Comment by makiisthenes** [comment]
In the error is says: "setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10."

NumPy 1.21.2 may not yet support Python 3.10. So use a older version of Python 3.
