### ISSUE TITLE
Either Bot crashes, or the site doesn't allow you to login

### ISSUE THREAD

**Issue by Another-Man** [makiisthenes/TiktokAutoUploader#13]
Hello there!

I ran into a problem, which is mostly described in a header:
So, when I start the Bot up, it opens a session in a browser like it should, it redirects to upload link like it should, but then there is a login procedure - that's where it struggles.
Basically, in the console I type in the index of a cookie I need, then bot loads up this cookie without a password (which is understandable from a security stand point, I just don't know if it shouldn't save the password), waits for a second or two and terminates the session, terminating himself with an error:

![image](https://user-images.githubusercontent.com/63965948/135331921-5cf0f5cc-149c-4c8c-bfe8-091debff442d.png)

First of all, I can't type in the password for the account in a given time frame (before Bot terminates the session), it is very small.
Secondly, if I were to login manually (say, I wanted to create a new cookie), something is still preventing me from logging in, creating this error message:

![image](https://user-images.githubusercontent.com/63965948/135332446-c9922d60-2566-4820-b41d-f8d1f9f28711.png)

... which is absurd, because at that moment this is the only session for this account. Given being a little paranoid about my own capabilities, I checked if I could log in this account in other browsers and on other devices - no problem, only in Bot's session.

It would be great if you could help me solve my problem ASAP!
Or, for that matter, could help to point out the problem more accurately, the Google is likely sufficient for further troubleshooting.

**Comment by Another-Man** [comment]
I forgot to add, that tweaking the Bot.py file did not help (obviously, it couldn't because there is no upload button on the page).

**Comment by makiisthenes** [comment]
Usually when this occurs, it means tiktok knows this is a bot session, I will try update browser settings as an option instead of the undetected-chromedriver package used. However as of right now, there is nothing I could do, it does still work for most people, I have tried it myself as of right now. Will try fix soon, thanks for issue.

**Comment by tnusser** [comment]
This might be related to the issue of the changed HTML code by TikTok and the upload-video button now being nested inside an iframe. Could be fixed now, had similar issues with that too.

**Comment by makiisthenes** [comment]
Hi, this issue usually stops people from logging in desipite correct credentials. Will update repo with fixes.

**Comment by nickshanks347** [comment]
I get the too many attempts issue too....

**Comment by fedecech** [comment]
#39 Should almost completely solve this

**Comment by makiisthenes** [comment]
New version does not use selenium, and only requests, should work, please review.
