### ISSUE TITLE
Thanks for your share of this TiktokAutoUploader

### ISSUE THREAD

**Issue by sinoshon** [makiisthenes/TiktokAutoUploader#3]
Firstly, Thank you very much for your share of this TiktokAutoUploader. 

Could you update the function(TIKTOK multi-account management and batch automatic upload) of this application like the following videos?

[https://www.youtube.com/watch?v=-5h89yOwGqM](url)

Waiting for your update and Appreciate for your work and share!

Best Wishes for you

**Comment by makiisthenes** [comment]
Thank you, I am glad you appreciated this project, however this is not an issue. I am still working on this project but experimenting on a few things. Addition of more accounts can be done very easily by the tweaking of the Cookies.py and implementation of it. I will update code for this option in the very near future. Best

**Comment by sinoshon** [comment]
Great! If you finish it, please notice me any time, I would like to test it at first. Have a good day, Sir!

**Comment by sinoshon** [comment]
> Thank you, I am glad you appreciated this project, however this is not an issue. I am still working on this project but experimenting on a few things. Addition of more accounts can be done very easily by the tweaking of the Cookies.py and implementation of it. I will update code for this option in the very near future. Best

Hello, I found you have updated it yesterday. Thanks for your work! If you update it with GUI, I think we can cooperate and sell it in China by per month or per year subscription? How do you think it?

Thank you again!

Regards
Mountain

**Comment by makiisthenes** [comment]
Sounds great 👍
