### ISSUE TITLE
Adding emojis to the hashtags.txt?

### ISSUE THREAD

**Issue by MoltoDev** [makiisthenes/TiktokAutoUploader#31]
` f = open("hashtags.txt", "w", encoding="utf-8")
f.write("#funny 🚗 \r U+1F60A")
f.close()`

No matter what I try to do I can't make it post emojis when uploading?

**Comment by makiisthenes** [comment]
Are you sure you are using the correct encoding?

**Comment by MoltoDev213** [comment]
I've tried stuff like
🚗
/U+1F60A
U+1F60A

No matter how I put it into the hashtags.txt file it doesn't work

**Comment by makiisthenes** [comment]
This github repo has been updated
