### ISSUE TITLE
Why not use the TikTok API?

### ISSUE THREAD

**Issue by Sammeeey** [makiisthenes/TiktokAutoUploader#32]
Why creating such a workaround?
Doesn't the TikTok API allow automatic uploads - even scheduling uploads?🤔

**Comment by Zebraslive** [comment]
I might just have to build my own desktop app for uploading to tiktok using electron.js and Node.js since I hate python with a passion.

**Comment by p5quared** [comment]
> I might just have to build my own desktop app for uploading to tiktok using Node.js + electron since I hate python with a passion.

What problems will an electron app solve over a python script??? 🤔

**Comment by Zebraslive** [comment]
> > I might just have to build my own desktop app for uploading to tiktok using Node.js + electron since I hate python with a passion.
> 
> What problems will an electron app solve over a python script??? thinking

Desktop app with user interface, tracking statistics etc... and the best part is, no python.

**Comment by phiasco12** [comment]
> Why creating such a workaround?
> Doesn't the TikTok API allow automatic uploads - even scheduling uploads?🤔

because using API wont allow you to 'auto' post. you get a notification in the app and you have to manually go on the app and publish it.

**Comment by Sammeeey** [comment]
Thank you for the clear response @phiasco12 !
How do these companies who provide publishing API's do this then?🤔

**Comment by p5quared** [comment]
> How do these companies who provide publishing API's do this then?🤔
Looking at a few: using Selenium.

> because using API wont allow you to 'auto' post. you get a notification in the app and you have to manually go on the app and publish it.
What is the point of having an upload endpoint in the API if you cannot call it? Or do you mean that the videos are uploaded to TikTok but you must "confirm" from your account by hand?

**Comment by Sammeeey** [comment]
> Looking at a few: using Selenium.

That's scary😱
Sounds like a foolproof way to get banned if you ask me.😅


> What is the point of having an upload endpoint in the API if you cannot call it? Or do you mean that the videos are uploaded to TikTok but you must "confirm" from your account by hand?

Second one: I'd like to schedule automatically from my server and then have it in my phone, ready to edit & publish.
But seems like the draft posts can only be created on the phone and saved locally - but not created from the API & then published using the phone.

**Comment by 546200350** [comment]
Maybe you can try https://github.com/546200350/TikTokUploder.
a python script, just useing the Tiktok API to upload video.
