### ISSUE TITLE
No idea how to use

### ISSUE THREAD

**Issue by Zenahr** [makiisthenes/TiktokAutoUploader#34]
The v1 files are out of date (why not remove all of that code, delete the v2 folder and have v2 be the "default" project?)
When running v2, I run into countless errors, such as `AttributeError: 'Chrome' object has no attribute 'WebDriverWait'`
I don't know where to begin with this, no clue what's working and what's supposed to be working.

**Comment by makiisthenes** [comment]
New version with guide and clutter removed will be added, as well as PyPI package for easier install.
