### ISSUE TITLE
Ok i am going to ask the obvious: how to store cookies?

### ISSUE THREAD

**Issue by sensahin** [makiisthenes/TiktokAutoUploader#35]
Pls?

**Comment by hlhudson** [comment]
ok i am going to ask the oblivious: why would you want to store cookies?

**Comment by 546200350** [comment]
Maybe you can try https://github.com/546200350/TikTokUploder.
a python script, just useing the Tiktok API to upload video.

**Comment by fedecech** [comment]
Hey @sensahin, better later than never I guess... 
The `Browser` class provides everything you need. It stores an instance of `Chrome` web driver, that you can access and on that instance you can add, remove, modify cookies. From there you can save them on filesystem ecc.

Maybe you should have a look at [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver), the selenium driver that we are using and more in general also you can have a look at: [selenium documentation](https://www.selenium.dev/documentation/)

Hope this helps. :)
