### ISSUE TITLE
I want this, but dont know where to start.....

### ISSUE THREAD

**Issue by REALtony4twenty** [makiisthenes/TiktokAutoUploader#36]
I have minimum knowledge of using python scripts. I have used some to generate TTS and grab a random photo from unsplash...etc... but someone Please guide me through everything including what button to push to download the things I need here lol. I dont see a .zip that contains the files and that always stops me in my tracks.

**Comment by 546200350** [comment]
Maybe you can try https://github.com/546200350/TikTokUploder.
a python script, just useing the Tiktok API to upload video.

**Comment by makiisthenes** [comment]
Working on a user friendly guide with a more up to date faster service for this.
