### ISSUE TITLE
cant know how to use this perferct application

### ISSUE THREAD

**Issue by stevenwong21** [makiisthenes/TiktokAutoUploader#4]
I have installed "pip install -r requirements.txt" successfully, but when I run "python main.py", the error mention is following:

PS E:\TT\TiktokAutoUploader-master> python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from Upload import Upload
  File "E:\TT\TiktokAutoUploader-master\Upload.py", line 3, in <module>
    from pytube import YouTube
ModuleNotFoundError: No module named 'pytube'
PS E:\TT\TiktokAutoUploader-master> 

And I don't know how to set the schedule upload time, could you make the short video to explain how to use this wonderful application?

Thanks and Have a nice day!

Regards,
Steven

**Comment by makiisthenes** [comment]
Given its giving you a ModuleNotFoundError, are you sure you have set up your environment correctly? All necessary modules are in requirements.txt including pytube. Scheduling does not work as of right now.
