### ISSUE TITLE
本地上传问题

### ISSUE THREAD

**Issue by Zuul01** [makiisthenes/TiktokAutoUploader#5]
本地上传登录后不能自动上传和填充标题，下次启动没有存放cookide，不能自动登录

**Comment by makiisthenes** [comment]
我今天更新这个，提交是中间步骤

**Comment by makiisthenes** [comment]
我今天更新这个，提交是一个中间步骤

**Comment by Zuul01** [comment]
> 我今天更新这个，提交是一个中间步骤

Looking forward to your update, can run normally

**Comment by makiisthenes** [comment]
You can now use multiple accounts on tiktok.
