### ISSUE TITLE
how to user proxy with auth?

### ISSUE THREAD

**Issue by zerofishy** [makiisthenes/TiktokAutoUploader#51]
usage: cli.py upload [-h] -c COOKIE -v VIDEO -t TITLE [-sc SCHEDULE] [-ct {0,1}] [-d {0,1}] [-st {0,1}] [-vi VISIBILITY] [-bo BRANDORGANIC] [-bc BRANDCONTENT]
                     [-ai AILABEL] [-p PROXY]                                                                                                                 
cli.py upload: error: argument -p/--proxy: invalid int value: 'http://3333:wwhJdG@38.152.244.169:1111'

**Comment by makiisthenes** [comment]
I have now updated the code to accept proxies, use can now add proxy urls which will set when sending requests.

**Comment by zerofishy** [comment]
tyty
