### ISSUE TITLE
Login Issues: Cookies File

### ISSUE THREAD

**Issue by Festouille** [makiisthenes/TiktokAutoUploader#53]
Hello, I tried your new version and i got issues with login, I don't understand how can I get the cookies, or login, can u help me with it ? I tried to use the help option but didn't help, and it's not really clear on your documentation ! thank you

**Comment by makiisthenes** [comment]
# Using current CLI commands to store cookies,
Currently there is one way to obtain these cookies, 

`python cli.py login -n username`

This will open up a chrome window, which will prompt you to login to Tiktok, please make sure you have the latest version of Chrome installed on your system.

When logged in this cookie will be saved on your system, to view all cookies currently on system, use command:

`python cli.py show -c `

This will ensure that you can upload videos using that exact username, through command:


`python cli.py upload --user username -v "video.mp4" -t "My video title" `


# Manually add cookies using browser
Alternatively, you may want to obtain cookies manually, to do so, 

By using tiktok cookies function `save_cookies_to_file`

for the object to be saved, input the following:

```python
cookies = [{'domain': '.tiktok.com', 'expiry': EXPIRY_FROM_BROWSER, 'httpOnly': True, 'name': 'sessionid', 'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': 'YOUR_SESSION_KEY_FROM_BROWSER'}]

save_cookies_to_file(cookies, "username.cookie")  # You must have the .cookie extension.

```

**Comment by dinhho99899** [comment]
Hi, I use CLI commands to get cookie but Chrome instance close immediately
When i using : 
from tiktok_uploader.cookies import save_cookies_to_file
cookies = [{'domain': '.tiktok.com', 'expiry': '2024-08-19T15:16:23.261Z', 'httpOnly': True, 'name': 'sessionid', 'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': '6941a453aeed32ca8e5fbcb03fb0ce34'}]
save_cookies_to_file(cookies, "username.cookie")
It creates username.cookie.cookie (���)
And when **python cli.py show -u** -->User Names logged in: 
It means no use on system
Tks
