### ISSUE TITLE
Task Request Error

### ISSUE THREAD

**Issue by makiisthenes** [makiisthenes/TiktokAutoUploader#57]
> ![image](https://private-user-images.githubusercontent.com/115322112/305185350-045c41b4-acc2-487c-ab96-88e53e7b37da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODk5MTYsIm5iZiI6MTcwODA4OTYxNiwicGF0aCI6Ii8xMTUzMjIxMTIvMzA1MTg1MzUwLTA0NWM0MWI0LWFjYzItNDg3Yy1hYjk2LTg4ZTUzZTdiMzdkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxMzIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjExZThhZGQ2ODI5N2RkODAwMzVkMTNmYWE4MzU4Mjc3NGJmZjBiMzA3MDA0YjQ1ZDE0ZTIwYmY3MGE2ZDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TOzywOjRNrESBZv-8VB8EVncHn6N2MvAYN3rAfM0-6Q)
> 
> Worked using Python 3.10 !

I using python 3.10.10 with latest source commit. But getting the following error. Does anyone know how to fix it?
![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/31133376/5e2c11ec-b472-40d7-b51f-4a628c2d634b)

_Originally posted by @HoTruong in https://github.com/makiisthenes/TiktokAutoUploader/issues/52#issuecomment-1948379695_

**Comment by download2Play** [comment]
Looks like this url needs _signature how to generate _signature
https://www.tiktok.com/api/v1/web/project/post/?app_name=tiktok_web&channel=tiktok_web&device_platform=web&aid=1988&msToken={mstoken}&X-Bogus={xbogus}

**Comment by HoTruong** [comment]
> generate _signature

Thank you for your information. However, I'm not sure how to generate the _signature. Can you explain more? Do I need to generate a TikTok signature token using Node?

**Comment by makiisthenes** [comment]
Error is that they changed the API to include _signature, this has been fixed, however you require node.
