### ISSUE TITLE
Session Id not found 

### ISSUE THREAD

**Issue by PluttoX** [makiisthenes/TiktokAutoUploader#58]
User not found on system.
No cookie with Tiktok session id found: use login to save session id
I am login to my acccount and when we run this command "cli.py login -n corelessgaming
"
open my cli.py file

**Comment by PluttoX** [comment]
(tictokbotenv) C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main>python cli.py upload --user my_saved_username -yt "https://www.youtube.com/shorts/90AeypnHyWg" -t "My video title"
Detected Youtube Video...
Starting Download for Video...
User not found on system.
No cookie with Tiktok session id found: use login to save session id

**Comment by PluttoX** [comment]
(tictokbotenv) C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main>python cli.py show -u
User Names logged in:

(tictokbotenv) C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main>

**Comment by PluttoX** [comment]
![issue](https://github.com/makiisthenes/TiktokAutoUploader/assets/148310269/a4f84b2a-2aec-4e7b-9752-e545e8d25004)
When We run python cli.py login -n username This error will occur on screenshoot

**Comment by makiisthenes** [comment]
This was an issue with https://github.com/ultrafunkamsterdam/undetected-chromedriver
I have updated the package used to 3.5.5, 
Please reinstall requirements from latest commit.
