### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 89

### ISSUE THREAD

**Issue by franzqat** [makiisthenes/TiktokAutoUploader#6]
Hello, I tried to run this but I got the error from selenium

> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
> Current browser version is 91.0.4472.101

Since in the readme you said to use the chromedriver that you provided, can you please update it or explain which changes have you done?

**Comment by makiisthenes** [comment]
Hi there, thanks for letting me know, I have updated the chromedriver file to version 91.0.4472.101
