### ISSUE TITLE
How can I skip video editing(MoviePy and ImageMagick)

### ISSUE THREAD

**Issue by Tawny75** [makiisthenes/TiktokAutoUploader#7]
Hello, all I need is only taking the video.mp4 file and uploading it to TikTok without modifiyng it with MoviePy and ImageMagick, do you know how I can skip/remove the video editing please? Because I tried and it broke the code so pretty hard for me to understand as im newbie in py
thanks

**Comment by makiisthenes** [comment]
You can do that by adding no start and end parameters to stop cropping of video, currently, there is no feature to not allow direct upload, but will do this after fixing cookies to handle multiple accounts.

**Comment by makiisthenes** [comment]
I have now added direct upload feature so you can just input a video and it will upload as it.
