### ISSUE TITLE
Issue with schedule option

### ISSUE THREAD

**Issue by Zowlak** [makiisthenes/TiktokAutoUploader#72]
**UPDATED : NOW ISSUE WITH SCHEDULE OPTION**

Hello, when I try to use the schedule option, it's not working.
It return me : [-] Video could not be uploaded: Invalid parameters

Have you an idea to fix?

**Comment by Zowlak** [comment]
Resolved for this part, now i'm looping into "[-] Waiting for TikTok to process video..." or connection timed-out, even if i'm using proxies
Maybe i'm using wrong proxies, have u any recommandation?

**Comment by Zowlak** [comment]
Now it works but the scheduled option didn't, it return me : [-] Video could not be uploaded: Invalid parameters
Have you an idea to fix?

**Comment by BHK-Industry** [comment]
How does the code for schedule option look like?

**Comment by BHK-Industry** [comment]
```
PS C:\Users\hadik\TiktokAutoUploader> python cli.py upload --user bhk.cloud -yt "https://www.youtube.com/shorts/0A4XfPveeLU" -t "FREE BHK Cloud Gaming NOW" -sc 1713053374
Detected Youtube Video...
Starting Download for Video...
User successfully logged in.
Tiktok Datacenter Assigned: useast2a
Uploading video...
[-] Cannot schedule video in more than 10 days or less than 20 minutes
```

**Comment by makiisthenes** [comment]
Hello, this is not a issue, you are not able to schedule more than 10 days in advance, in other words, the maximum flag integer that can be entered is `864000` seconds (10 days) and minimum is `1200` seconds (20 mins), you have entered `1713053374`

**Comment by Zowlak** [comment]
In my case, that's not my issue. 
When I put a right schedule (for exemple : 3600 = 1 hour), i got this error message : 
[-] Video could not be uploaded: Invalid parameters

See my prompt : 
<img width="1229" alt="image" src="https://github.com/makiisthenes/TiktokAutoUploader/assets/76110476/779c50ce-41a7-42f2-93d8-81e08925841c">

Result : 
<img width="1272" alt="image" src="https://github.com/makiisthenes/TiktokAutoUploader/assets/76110476/ea9b2417-aed2-48fd-8e51-dddc8e5d51ea">
