### ISSUE TITLE
It is incredibly slow for me, to upload 15 sec videos, can I improve upload speed?

### ISSUE THREAD

**Issue by felipexpert** [makiisthenes/TiktokAutoUploader#73]
It is incredibly slow for me, to upload 15 sec videos, can I improve upload speed?

**Comment by makiisthenes** [comment]
Hi, from the scripts side, we have uploaded the video, there is a internal loop that polls tiktok for a confirmation, so this slow speed is dependant on TikTok and also some have said proxy help. Thanks.

**Comment by makiisthenes** [comment]
This has been updated.
