### ISSUE TITLE
ERR_NETWORK_CHANGED 

### ISSUE THREAD

**Issue by OurLobanov** [makiisthenes/TiktokAutoUploader#89]
User successfully logged in.
Tiktok Datacenter Assigned: useast1a
Uploading video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
page.goto: net::ERR_NETWORK_CHANGED at https://www.tiktok.com/api/v1/web/project/post/?app_name=tiktok_web&channel=tiktok_web&device_platform=web&aid=1988&msToken=ТОКЕН
Call log:
  - navigating to "https://www.tiktok.com/api/v1/web/project/post/?app_name=tiktok_web&channel=tiktok_web&device_platform=web&aid=1988&msToken=ТОКЕН-OmVU5O07J6eHaFELOYJfsDxX2o=", waiting until "networkidle"

    at Signer.init (C:\Users\kloba\Desktop\tiktok\tiktok_uploader\tiktok-signature\index.js:73:21)
    at async main (C:\Users\kloba\Desktop\tiktok\tiktok_uploader\tiktok-signature\browser.js:9:5) {
  name: 'Error'
}

After that, it freezes forever, the script does not close, does nothing

**Comment by makiisthenes** [comment]
This has been fixed, no longer polls, uploads instantly...
