### ISSUE TITLE
make it deployable on heroku & direct link as input

### ISSUE THREAD

**Issue by claimclone** [makiisthenes/TiktokAutoUploader#9]
Hi Michael ,
please make it deployable on heroku free dyno for work autopilot & fully free. also heroku have wide range of buildpacks like imagemagick , chrome headless , ffmpeg , 
.. & using set workers in Procfile , u can autorun important cmds after awake dyno from daily sleep.
waiting for your changes commits :)
finest regards
goodbye

**Comment by makiisthenes** [comment]
Sorry, thanks for this suggestion, but I don't plan on doing this. Best, Michael.

**Comment by desk-lamp** [comment]
lol
