### ISSUE TITLE
{'log_pb': {'impr_id': '202411291550206F81B125BDBEB6890A6A'}, 'status_code': 403, 'status_msg': ''}

### ISSUE THREAD

**Issue by Realman23** [makiisthenes/TiktokAutoUploader#93]
Video upload: Traceback (most recent call last):
  File "/path/to/project/tiktok-auto-uploader/cli.py", line 76, in <module>
    tiktok.upload_video(args.users, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "/path/to/project/tiktok-auto-uploader/tiktok_uploader/tiktok.py", line 228, in upload_video
    if j["tasks"][0]["status_msg"] == "Y project task init" or j["tasks"][0]["status_msg"] == "Success":
KeyError: 'tasks'

As I understand, tiktok has changed their endpoints or endpoints which have been used in this project are obsolete. Now it is showing 403 error. Can you please fix it?

**Comment by DelvinBa** [comment]
I will try to figure out what the problem is, when you find the solution, please post it here too.

**Comment by Realman23** [comment]
> I will try to figure out what the problem is, when you find the solution, please post it here too.

What I`ve noticed. There are two global steps of downloading your video to the tiktok. Upload and post. Upload is working. In tiktok there is a function, if you successfully uploaded your file, but not posted and go away, the, if you return it will open a dialog box, where will be info about your previous draft. It stores 5 most recent drafts, however in user side it is shown only as the last one previous. If you will comment out on 225 line in tiktok.py `print(r.json()["infos"]`, it will print out all info about previous uploaded files. (In this list there are creationID, projectID, etc.).
**Why upload works?**
Because after each 403 error, this list of r.json()["infos"] updates with one new element, which is your previous uploaded file.
So I think, that problem is in the post part. As I debugged, some of the requests are obsolete. F.e., in 276 line this request URL: `https://{upload_host}/{store_uri}?partNumber={i + 1}&uploadID={upload_id}&phase=transfer` is missing `upload/v1` after {upload_host}. This URL: `https://www.tiktok.com/api/v1/web/project/post/?app_name=tiktok_web&channel=tiktok_web&device_platform=web&aid=1988&msToken={mstoken}` api needs to be replaced with tiktok in this version. So every link has been changed somehow and I guess, that a way how to process data from these request url`s also is changed.

**Comment by DelvinBa** [comment]
I think you are right. I uploaded a Video manually and had a look on the network tab in chrome debugger. Indeed the upload endpoint did not change, but the post request upload changed from 
`https://www.tiktok.com/api/v1/web/project/post/`
to
`https://www.tiktok.com/tiktok/web/project/post/v1/`.
I changed that in the code and now I got invalid parameters instead of an 403 error. So I think I am on the right track. But yes, still needs deep research and I hope they only changed the syntax and not the semantics of the endpoints.

Also I saw, that this r.json() does not contain the key 'tasks' anymore. Either it was because of wrong endpoints used before, or this is just not in the response anymore.

**Comment by daytradertools** [comment]
I've got the same error and I'm glad you are already investigating this. 👍

**Comment by daytradertools** [comment]
Any news about this?

**Comment by makiisthenes** [comment]
@DelvinBa  Do you want to make PR request, or I can test and add this to new commit

**Comment by DelvinBa** [comment]
@makiisthenes you can test and add this to new commit

**Comment by makiisthenes** [comment]
Changes were made, thanks for figuring this out, added your contribution to readme!
