### ISSUE TITLE
How to Fix upload scheduling

### ISSUE THREAD

**Issue by jongan69** [makiisthenes/TiktokAutoUploader#94]
Inside `tiktok_uploader/tiktok.py`

at line 231 

change:
`data["upload_param"]["schedule_time"] = schedule_time + int(time.time())`

to: 
`data["feature_common_info_list"][0]["schedule_time"] = schedule_time + int(time.time())`

perhap tiktok updated their api, had to manually schedule a post and find the api post request body to solve this.

**Comment by makiisthenes** [comment]
Will add this, thanks for input.
